language:       scala
scala:
              - 2.12.10
jdk:
              - openjdk8
              - oraclejdk8
dist:           trusty
cache:
  directories:
              - $HOME/.ivy2/cache
              - $HOME/.sbt/boot/
install:
              - sudo apt-get update
              - sudo apt-get install zsh
              - sudo chmod +x scripts/*
              - ./sbt update
script:         ./sbt fullTest
after_script:
              - scripts/prepare-test-results-for-ci.sh
              - find $HOME/.sbt -name "*.lock" | xargs rm
              - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
notifications:
  email:
    on_success: never
    on_failure: change
